/* Generated By:JavaCC: Do not edit this line. CommandInterpreterConstants.java */
package de.fhg.iese.cl.parser;

public interface CommandInterpreterConstants {

  int EOF = 0;
  int HELP = 4;
  int EXIT = 5;
  int SHOWPROPERTIES = 6;
  int SETPROPERTIES = 7;
  int ADDCOREASSET = 8;
  int SHOWCOREASSETS = 9;
  int SHOWINSTANCES = 10;
  int INSTANTIATECOREASSET = 11;
  int SHOWINSTANCEDIFF = 12;
  int SHOWCOREDIFF = 13;
  int REBASE = 14;
  int INTEGRATE = 15;
  int CLEAR = 16;
  int MINUS_D = 17;
  int NUMBER = 18;
  int PATH = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"help\"",
    "\"exit\"",
    "\"show-properties\"",
    "\"set-properties\"",
    "\"add-core-asset\"",
    "\"show-core-assets\"",
    "\"show-instances\"",
    "\"instantiate-core-asset\"",
    "\"show-instance-diff\"",
    "\"show-core-diff\"",
    "\"rebase\"",
    "\"integrate\"",
    "\"clear\"",
    "\"-d\"",
    "<NUMBER>",
    "<PATH>",
  };

}
